<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKiqbcfq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKiqbcfq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKiqbcfq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKiqbcfq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKiqbcfq\appProdProjectContainer(array(
    'container.build_hash' => 'Kiqbcfq',
    'container.build_id' => '3d623510',
    'container.build_time' => 1542118968,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKiqbcfq');
